//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawMusicWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_Data
    {
        public string album { get; set; }
        public string artist { get; set; }
        public string slug { get; set; }
        public string urlalbum { get; set; }
        public string image { get; set; }
        public string year { get; set; }
        public Nullable<int> countSongs { get; set; }
        public int Id { get; set; }
    }
}
