//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawMusicWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ms_Song()
        {
            this.ms_Album = new HashSet<ms_Album>();
            this.ms_Artist = new HashSet<ms_Artist>();
            this.ms_Collection = new HashSet<ms_Collection>();
            this.ms_Genre = new HashSet<ms_Genre>();
        }
    
        public int Id { get; set; }
        public int AlbumId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public string MediaUrl { get; set; }
        public string Lyrics { get; set; }
        public Nullable<int> Status { get; set; }
        public string Url { get; set; }
        public Nullable<double> Duration { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<double> Quality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_Album> ms_Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_Artist> ms_Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_Collection> ms_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ms_Genre> ms_Genre { get; set; }
    }
}
